---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret cross-seed-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-secretstore
  target:
    name: *secret
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      data:
        config.js: |
          function fetchIndexers(baseUrl, apiKey, tag){
            const buffer = require('child_process').execSync(`curl -fsSL "$${baseUrl}/api/v1/tag/detail?apikey=$${apiKey}"`);
            const response = JSON.parse(buffer.toString('utf8'));
            const indexerIds = response.filter(t => t.label === tag)[0]?.indexerIds ?? [];
            const indexers = indexerIds.map(i => `$${baseUrl}/$${i}/api?apikey=$${apiKey}`);
            console.log(`Loaded $${indexers.length} indexers from Prowlarr`);
            return indexers;
          }
          module.exports = {
            action: "inject",
            apiKey: "{{ .cross_seed_api_key }}",
            linkCategory: "cross-seed",
            linkDirs: ["/data/media/downloads/torrents/complete/cross-seed"],
            linkType: "hardlink",
            matchMode: "partial",
            radarr: ["http://radarr.downloads.svc.cluster.local:7878/?apikey={{ .radarr_api_key }}"],
            skipRecheck: true,
            sonarr: ["http://sonarr.downloads.svc.cluster.local:8989/?apikey={{ .sonarr_api_key }}"],
            torrentClients: ["qbittorrent:http://qbittorrent.downloads.svc.cluster.local:8080"],
            torznab: fetchIndexers("http://prowlarr.downloads.svc.cluster.local:9696", "{{.prowlarr_api_key}}", "cross-seed"),
            useClientTorrents: true
          }

  data:
    - secretKey: cross_seed_api_key
      remoteRef:
        key: downloads/cross-seed/config
        property: api_key

    - secretKey: prowlarr_api_key
      remoteRef:
        key: downloads/prowlarr/config
        property: api_key

    - secretKey: radarr_api_key
      remoteRef:
        key: downloads/radarr/config
        property: api_key

    - secretKey: sonarr_api_key
      remoteRef:
        key: downloads/sonarr/config
        property: api_key
