---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app household-postgres
  namespace: flux-system
spec:
  targetNamespace: &namespace household
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: cnpg-operator
      namespace: flux-system
  path: ./kubernetes/apps/household/database/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *namespace
      NAMESPACE: *namespace
      POSTGRES_VERSION: "18.1-3.6.1-system-trixie@sha256:2ed181bc7e5e6a66b3b4718bd08617fca258d2f28b9c75b2e69e753840edc818"
      POSTGRES_MEMORY_LIMIT: "4Gi"
      POSTGRES_IMAGE_NAME: "postgis"
      POSTGRES_ENABLE_SUPERUSER: "true"
      POSTGRES_STORAGE_CLASS: truenas-iscsi
      POSTGRES_BACKUP_SCHEDULE: "30 5 * * *"
