---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: manyfold-secret
  namespace: maker
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-secretstore
  target:
    name: manyfold-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        SECRET_KEY_BASE: "{{ .manyfold_config_secret_key }}"
        OIDC_ISSUER: "https://auth.${SECRET_DOMAIN}/application/o/manyfold/"
        OIDC_CLIENT_ID: "{{ .manyfold_oidc_client_id }}"
        OIDC_CLIENT_SECRET: "{{ .manyfold_oidc_client_secret }}"
        OIDC_NAME: "Authentik"
        FORCE_OIDC: "enabled"
  data:
    - secretKey: manyfold_config_secret_key
      remoteRef:
        key: maker/manyfold/credentials
        property: manyfold_config_secret_key

    - secretKey: manyfold_oidc_client_id
      remoteRef:
        key: maker/manyfold/oidc
        property: client_id
    - secretKey: manyfold_oidc_client_secret
      remoteRef:
        key: maker/manyfold/oidc
        property: client_secret
