---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-backups
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: truenas-nfs-backups
  resources:
    requests:
      storage: 50Gi
