---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: audiobookshelf-secret
  namespace: media
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-secretstore
  target:
    name: audiobookshelf-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        JWT_SECRET_KEY: "{{ .JWT_SECRET }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        ENCRYPTION_KEY: "{{ .ENCRYPTION_KEY }}"
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: media/audiobookshelf/credentials
        property: JWT_SECRET
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: media/audiobookshelf/credentials
        property: ENCRYPTION_KEY
