---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app open-webui
  namespace: flux-system
spec:
  targetNamespace: &namespace ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  # components:
  #   - ../../../../components/volsync
  dependsOn:
    - name: searxng
      namespace: *namespace
    - name: volsync
      namespace: system
    - name: traefik
      namespace: network
    - name: openbao
      namespace: external-secrets
  path: ./kubernetes/apps/ai/open-webui/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      VOLSYNC_CLAIM: open-webui-config
      VOLSYNC_CAPACITY: 20Gi
      VOLSYNC_REPOSITORY_NAMESPACE: *namespace
      VOLSYNC_CACHE_CAPACITY: 60Gi
