---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app bookshelf
spec:
  targetNamespace: &namespace downloads
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
    - ../../../../components/common/secrets
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: downloads-postgres
  interval: 1h
  path: ./kubernetes/apps/downloads/bookshelf/audio
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: bookshelf-config
      VOLSYNC_REPOSITORY_NAMESPACE: *namespace
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ebookshelf
spec:
  targetNamespace: &namespace downloads
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
    - ../../../../components/common/secrets
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: downloads-postgres
  interval: 1h
  path: ./kubernetes/apps/downloads/bookshelf/ebook
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: ebookshelf-config
      VOLSYNC_REPOSITORY_NAMESPACE: *namespace
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 5m
  wait: false
