---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace downloads
components:
  - ../../components/common
  - ../../components/flux/alerts
resources:
  - ./autobrr/ks.yaml
  - ./audiobookrequest/ks.yaml
  - ./bazarr/ks.yaml
  - ./bookshelf/ks.yaml
  - ./cross-seed/ks.yaml
  - ./database/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./lidarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./rreading-glasses/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./seerr/ks.yaml
  - ./sonarr/ks.yaml
