---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: downloads
components:
  - ../../components/common
  - ../../components/flux/alerts
resources:
  # - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
