---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: &namespace downloads
components:
  - ../../components/common
  - ../../components/flux/alerts
resources:
  - ./bazarr/ks.yaml
  - ./cross-seed/ks.yaml
  - ./database/ks.yaml
  - ./lidarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./radarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./seerr/ks.yaml
  - ./sonarr/ks.yaml
patches:
  - target:
      kind: Namespace
      name: *namespace
    patch: |
      - op: add
        path: /metadata/labels
        value:
          pod-security.kubernetes.io/enforce: baseline
          pod-security.kubernetes.io/audit: baseline
          pod-security.kubernetes.io/warn: baseline
