apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/flux/alerts
resources:
  - ./cnpg/ks.yaml
  - ./dragonflydb/ks.yaml
  - ./influxdb/ks.yaml
  - ./pgadmin/ks.yaml
  - ./percona-mongodb/ks.yaml
  - ./namespace.yaml
