# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret vikunja-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-secretstore
  target:
    name: *secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # App
        VIKUNJA_SERVICE_JWT_SECRET: "{{ .vikunja_jwt_secret }}"
        VIKUNJA_DATABASE_HOST: &dbhost household-postgres-pooler.household.svc.cluster.local
        VIKUNJA_DATABASE_DATABASE: &dbname vikunja
        VIKUNJA_DATABASE_USER: &dbuser "vikunja"
        VIKUNJA_DATABASE_PASSWORD: &dbpass "{{ .DB_PASSWORD }}"

        # Postgres Init
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        # OIDC
        config.yml: |
          auth:
            local:
              enabled: false
            openid:
              enabled: true
              redirecturl: https://vikunja.${SECRET_DOMAIN}/auth/openid
              providers:
                - name: Authentik
                  authurl: https://auth.${SECRET_DOMAIN}/application/o/vikunja/
                  clientid: {{ .vikunja_oauth_client_id }}
                  clientsecret: {{ .vikunja_oauth_client_secret }}
                  scope: openid profile email

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "DB_PASSWORD"

  data:
    - secretKey: vikunja_oauth_client_id
      remoteRef:
        key: household/vikunja/oidc
        property: client_id
    - secretKey: vikunja_oauth_client_secret
      remoteRef:
        key: household/vikunja/oidc
        property: client_secret
    - secretKey: vikunja_jwt_secret
      remoteRef:
        key: household/vikunja/config
        property: jwt_secret

