---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app manyfold
  namespace: &namespace maker
spec:
  components:
    - ../../../../components/database/postgres
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/maker/manyfold/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  dependsOn:
    - name: openbao
      namespace: external-secrets
    - name: volsync
      namespace: system
    - name: manyfold-postres
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
    substitute:
      APP: *app
      VOLSYNC_CLAIM: manyfold-data
      VOLSYNC_CAPACITY: 5Gi
      NAMESPACE: *namespace
