---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../../../components/database/cluster
patches:
  - patch: |-
      apiVersion: postgresql.cnpg.io/v1
      kind: Cluster
      metadata:
        name: ${APP}-postgres
        namespace: ${NAMESPACE}
      spec:
        bootstrap:
          initdb:
            postInitTemplateSQL:
              - CREATE EXTENSION IF NOT EXISTS postgis;
              - CREATE EXTENSION IF NOT EXISTS postgis_topology;
