---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-postgres-minio
  namespace: ${NAMESPACE}
spec:
  secretStoreRef:
    name: openbao-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: ${APP}-postgres-minio
    creationPolicy: Owner
  data:
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: ${POSTGRES_MINIO_SECRET_PATH:=database/postgres/minio}
        property: access_key
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: ${POSTGRES_MINIO_SECRET_PATH:=database/postgres/minio}
        property: secret_key
