---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret sabnzbd-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-secretstore
  target:
    name: *secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        CROSS_SEED_API_KEY: "{{ .cross_seed_api_key }}"
        SABNZBD__API_KEY: "{{ .sabnzbd_api_key }}"
        SABNZBD__NZB_KEY: "{{ .sabnzbd__nzb_key }}"

  data:
    - secretKey: sabnzbd_api_key
      remoteRef:
        key: downloads/sabnzbd/config
        property: api_key
    - secretKey: sabnzbd__nzb_key
      remoteRef:
        key: downloads/sabnzbd/config
        property: nzb_key

    - secretKey: cross_seed_api_key
      remoteRef:
        key: downloads/cross-seed/config
        property: api_key
