---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-mysql-secrets
  namespace: ${NAMESPACE}
spec:
  secretStoreRef:
    name: openbao-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: ${APP}-mysql-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        root: "{{ .root_password }}"
        xtrabackup: "{{ .xtrabackup_password }}"
        monitor: "{{ .monitor_password }}"
        clustercheck: "{{ .clustercheck_password }}"
        operator: "{{ .operator_password }}"
  data:
    - secretKey: root_password
      remoteRef:
        key: ${MYSQL_SECRET_PATH:=database/${APP}/mysql}
        property: root_password
    - secretKey: xtrabackup_password
      remoteRef:
        key: ${MYSQL_SECRET_PATH:=database/${APP}/mysql}
        property: xtrabackup_password
    - secretKey: monitor_password
      remoteRef:
        key: ${MYSQL_SECRET_PATH:=database/${APP}/mysql}
        property: monitor_password
    - secretKey: clustercheck_password
      remoteRef:
        key: ${MYSQL_SECRET_PATH:=database/${APP}/mysql}
        property: clustercheck_password
    - secretKey: operator_password
      remoteRef:
        key: ${MYSQL_SECRET_PATH:=database/${APP}/mysql}
        property: operator_password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-mysql-backup-s3
  namespace: ${NAMESPACE}
spec:
  secretStoreRef:
    name: openbao-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: ${APP}-mysql-backup-s3
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_key }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: ${MYSQL_BACKUP_SECRET_PATH:=database/mysql/minio}
        property: access_key
    - secretKey: secret_key
      remoteRef:
        key: ${MYSQL_BACKUP_SECRET_PATH:=database/mysql/minio}
        property: secret_key
