---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: household
components:
  - ../../components/common
  - ../../components/common/secrets
  - ../../components/flux/alerts
resources:
  - ./adventurelog/ks.yaml
  - ./database/ks.yaml
  - ./glowing-bear/ks.yaml
  - ./mealie/ks.yaml
  - ./thelounge/ks.yaml
  - ./weechat/ks.yaml
