---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./intel-device-plugins/ks.yaml
  - ./k8tz/ks.yaml
  - ./kopia/ks.yaml
  - ./ksgate/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./volsync/ks.yaml
components:
  - ../../components/common
  - ../../components/flux/alerts
patches:
  - target:
      kind: Namespace
    patch: |
      - op: add
        path: /metadata/labels
        value:
          k8tz.io~1controller-namespace: true
