---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: auth
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-secretstore
  target:
    name: authentik-secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # Database Configuration (CNPG)
        AUTHENTIK_POSTGRESQL__HOST: "authentik-database-rw.auth.svc.cluster.local"
        AUTHENTIK_POSTGRESQL__PORT: "5432"
        AUTHENTIK_POSTGRESQL__NAME: "authentik"
        AUTHENTIK_POSTGRESQL__USER: "{{ .DB_USERNAME }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .DB_PASSWORD }}"
        AUTHENTIK_POSTGRESQL__SSL_MODE: "require"
        # Minio Storage Configuration
        AUTHENTIK_STORAGE__MEDIA__BACKEND: "s3"
        AUTHENTIK_STORAGE__MEDIA__S3__ACCESS_KEY: "{{ .MINIO_ACCESS_KEY }}"
        AUTHENTIK_STORAGE__MEDIA__S3__SECRET_KEY: "{{ .MINIO_SECRET_KEY }}"
        AUTHENTIK_STORAGE__MEDIA__S3__BUCKET_NAME: "authentik-media"
        AUTHENTIK_STORAGE__MEDIA__S3__REGION: "us-east-1"
        AUTHENTIK_STORAGE__MEDIA__S3__ENDPOINT: "https://s3.${SECRET_DOMAIN}"
        AUTHENTIK_STORAGE__MEDIA__S3__USE_SSL: "true"
        AUTHENTIK_STORAGE__MEDIA__S3__CUSTOM_DOMAIN: "s3.${SECRET_DOMAIN}/authentik-media"
        # Authentik Configuration
        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .BOOTSTRAP_EMAIL }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .BOOTSTRAP_PASSWORD }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .BOOTSTRAP_TOKEN }}"
        AUTHENTIK_SECRET_KEY: "{{ .SECRET_KEY }}"
        AUTHENTIK_ERROR_REPORTING__ENABLED: "false"
        AUTHENTIK_LOG_LEVEL: "info"
        # SMTP Configuration
        AUTHENTIK_EMAIL__HOST: "{{ .MAIL_SERVER_HOST }}"
        AUTHENTIK_EMAIL__PORT: "{{ .MAIL_SERVER_PORT }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .MAIL_SERVER_USERNAME }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .MAIL_SERVER_PASSWORD }}"
        AUTHENTIK_EMAIL__USE_TLS: "{{ .MAIL_USE_TLS }}"
        AUTHENTIK_EMAIL__USE_SSL: "{{ .MAIL_USE_SSL }}"
        AUTHENTIK_EMAIL__FROM: "{{ .MAIL_FROM_ADDRESS }}"
        AUTHENTIK_EMAIL__TIMEOUT: "{{ .MAIL_TIMEOUT }}"
  data:
    - secretKey: DB_USERNAME
      remoteRef:
        key: security/authentik/database
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: security/authentik/database
        property: password
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: security/authentik/storage
        property: access_key
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: security/authentik/storage
        property: secret_key
    - secretKey: BOOTSTRAP_EMAIL
      remoteRef:
        key: security/authentik/config
        property: bootstrap_email
    - secretKey: BOOTSTRAP_PASSWORD
      remoteRef:
        key: security/authentik/config
        property: bootstrap_password
    - secretKey: BOOTSTRAP_TOKEN
      remoteRef:
        key: security/authentik/config
        property: bootstrap_token
    - secretKey: SECRET_KEY
      remoteRef:
        key: security/authentik/config
        property: secret_key
    - secretKey: MAIL_SERVER_HOST
      remoteRef:
        key: security/authentik/config
        property: mail_server_host
    - secretKey: MAIL_SERVER_PORT
      remoteRef:
        key: security/authentik/config
        property: mail_server_port
    - secretKey: MAIL_SERVER_USERNAME
      remoteRef:
        key: security/authentik/config
        property: mail_server_username
    - secretKey: MAIL_SERVER_PASSWORD
      remoteRef:
        key: security/authentik/config
        property: mail_server_password
    - secretKey: MAIL_USE_TLS
      remoteRef:
        key: security/authentik/config
        property: mail_use_tls
    - secretKey: MAIL_USE_SSL
      remoteRef:
        key: security/authentik/config
        property: mail_use_ssl
    - secretKey: MAIL_FROM_ADDRESS
      remoteRef:
        key: security/authentik/config
        property: mail_from_address
    - secretKey: MAIL_TIMEOUT
      remoteRef:
        key: security/authentik/config
        property: mail_timeout
