# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &secret adventurelog-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao-cluster-secretstore
  target:
    name: *secret
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        GOOGLE_MAPS_API_KEY: "{{ .google_maps_api_key }}"
        DJANGO_ADMIN_PASSWORD: "{{ .admin_password }}"
        DJANGO_ADMIN_USERNAME: "{{ .admin_username }}"
        DJANGO_ADMIN_EMAIL: "{{ .admin_email }}"
        SECRET_KEY: "{{ .SECRET_KEY }}"

        PGHOST: &dbhost household-postgres-pooler.household.svc.cluster.local
        PGDATABASE: &dbname "adventurelog"
        PGUSER: &dbuser "adventurelog"
        PGPASSWORD: &dbpass "{{ .DB_PASSWORD }}"
        # --
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass

  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "DB_PASSWORD"

    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password64
      rewrite:
        - regexp:
            source: "password"
            target: "SECRET_KEY"

  data:
    - secretKey: admin_password
      remoteRef:
        key: household/adventurelog/credentials
        property: password
    - secretKey: admin_username
      remoteRef:
        key: household/adventurelog/credentials
        property: username
    - secretKey: admin_email
      remoteRef:
        key: household/adventurelog/credentials
        property: email

    - secretKey: google_maps_api_key
      remoteRef:
        key: household/adventurelog/config
        property: google_maps_api_key
