---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app downloads-postgres
  namespace: flux-system
spec:
  targetNamespace: &namespace downloads
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: cnpg-operator
      namespace: flux-system
  path: ./kubernetes/apps/downloads/database/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *namespace
      NAMESPACE: *namespace
      POSTGRES_VERSION: "18.1"
      POSTGRES_STORAGE_SIZE: "20Gi"
      POSTGRES_MEMORY_LIMIT: "4Gi"
      POSTGRES_ENABLE_SUPERUSER: "true"
      POSTGRES_STORAGE_CLASS: truenas-iscsi
      POSTGRES_BACKUP_SCHEDULE: "30 3 * * *"
